{"name": "test_login_invalid_user", "status": "passed", "start": 1727768737198, "stop": 1727768737342, "uuid": "8a7398a6-24b4-403c-91e3-d270d7821f9f", "historyId": "99420eee2c3e6c1d223ca72d74c63efd", "testCaseId": "99420eee2c3e6c1d223ca72d74c63efd", "fullName": "tests.test_auth.TestAuth#test_login_invalid_user", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "story", "value": "Логин с неверным логином и паролем"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "Asus.local"}, {"name": "thread", "value": "17694-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}